module.exports.coaches = [
  {
    fullname: "Aryan Sharma",
    dob: "1998-07-12",
    sport: "Cricket",
    state: "Maharashtra",
  },
  {
    fullname: "Vihaan Iyer",
    dob: "2001-05-23",
    sport: "Football",
    state: "Karnataka",
  },
  {
    fullname: "Kabir Mehta",
    dob: "1999-11-17",
    sport: "Badminton",
    state: "Tamil Nadu",
  },
  {
    fullname: "Rohan Kapoor",
    dob: "1997-08-05",
    sport: "Hockey",
    state: "Punjab",
  },
  {
    fullname: "Aarav Bhatt",
    dob: "2000-06-21",
    sport: "Wrestling",
    state: "Haryana",
  },
  {
    fullname: "Devansh Patel",
    dob: "2002-09-10",
    sport: "Boxing",
    state: "West Bengal",
  },
  {
    fullname: "Eshaan Gupta",
    dob: "1995-10-14",
    sport: "Shooting",
    state: "Uttar Pradesh",
  },
  {
    fullname: "Aadi Reddy",
    dob: "1996-12-03",
    sport: "Tennis",
    state: "Goa",
  },
  {
    fullname: "Nihal Rao",
    dob: "1994-04-07",
    sport: "Athletics",
    state: "Telangana",
  },
  {
    fullname: "Rudra Kulkarni",
    dob: "1998-03-15",
    sport: "Table Tennis",
    state: "Madhya Pradesh",
  },
  {
    fullname: "Arjun Mishra",
    dob: "1997-07-08",
    sport: "Swimming",
    state: "Rajasthan",
  },
  {
    fullname: "Vivaan Nair",
    dob: "2003-01-29",
    sport: "Basketball",
    state: "Kerala",
  },
  {
    fullname: "Raghav Joshi",
    dob: "2001-02-12",
    sport: "Volleyball",
    state: "Gujarat",
  },
  {
    fullname: "Parth Yadav",
    dob: "1993-11-30",
    sport: "Weightlifting",
    state: "Assam",
  },
  {
    fullname: "Anay Sen",
    dob: "1999-06-18",
    sport: "Gymnastics",
    state: "Chhattisgarh",
  },
  {
    fullname: "Shivam Choudhury",
    dob: "1995-09-25",
    sport: "Kabaddi",
    state: "Jharkhand",
  },
  {
    fullname: "Harsh Saxena",
    dob: "1996-05-04",
    sport: "Cycling",
    state: "Uttarakhand",
  },
  {
    fullname: "Reyansh Kapoor",
    dob: "2000-07-09",
    sport: "Chess",
    state: "Bihar",
  },
  {
    fullname: "Kunal Mukherjee",
    dob: "1994-10-22",
    sport: "Archery",
    state: "Odisha",
  },
  {
    fullname: "Ronit Das",
    dob: "2002-08-11",
    sport: "Judo",
    state: "Tripura",
  },
  {
    fullname: "Dhruv Bhargava",
    dob: "1993-12-05",
    sport: "Golf",
    state: "Himachal Pradesh",
  },
  {
    fullname: "Veer Trivedi",
    dob: "1997-03-28",
    sport: "Kho Kho",
    state: "Manipur",
  },
  {
    fullname: "Samar Paul",
    dob: "1998-09-14",
    sport: "Polo",
    state: "Meghalaya",
  },
  {
    fullname: "Ahaan Vashisth",
    dob: "2001-04-20",
    sport: "Carrom",
    state: "Nagaland",
  },
  {
    fullname: "Kian Sinha",
    dob: "1999-05-31",
    sport: "Shooting",
    state: "Arunachal Pradesh",
  },
  {
    fullname: "Neil Dutta",
    dob: "2003-10-16",
    sport: "Cricket",
    state: "Mizoram",
  },
  {
    fullname: "Rishit Rathi",
    dob: "1995-08-06",
    sport: "Football",
    state: "Sikkim",
  },
  {
    fullname: "Tanishq Mukherjee",
    dob: "2002-02-18",
    sport: "Badminton",
    state: "Andaman and Nicobar Islands",
  },
  {
    fullname: "Siddharth Jain",
    dob: "1998-06-12",
    sport: "Hockey",
    state: "Chandigarh",
  },
  {
    fullname: "Utsav Pandey",
    dob: "1996-09-27",
    sport: "Wrestling",
    state: "Dadra and Nagar Haveli and Daman and Diu",
  },
  {
    fullname: "Nirvaan Saxena",
    dob: "2000-11-05",
    sport: "Boxing",
    state: "Delhi",
  },
  {
    fullname: "Rohan Goel",
    dob: "2003-01-30",
    sport: "Tennis",
    state: "Lakshadweep",
  },
  {
    fullname: "Varun Soni",
    dob: "1997-12-21",
    sport: "Athletics",
    state: "Puducherry",
  },
  {
    fullname: "Neil Trivedi",
    dob: "1994-07-14",
    sport: "Table Tennis",
    state: "Ladakh",
  },
  {
    fullname: "Aryavir Singh",
    dob: "1995-04-09",
    sport: "Swimming",
    state: "Jammu and Kashmir",
  },
  {
    fullname: "Reetesh Mehta",
    dob: "2001-06-15",
    sport: "Basketball",
    state: "Goa",
  },
  {
    fullname: "Yash Rathi",
    dob: "1999-03-22",
    sport: "Volleyball",
    state: "Gujarat",
  },
  {
    fullname: "Ayaan Kapoor",
    dob: "1996-02-01",
    sport: "Weightlifting",
    state: "Maharashtra",
  },
];
