module.exports.players = [
  {
    fullname: "Aarav Sharma",
    dob: "2000-05-15",
    sport: "Cricket",
    state: "Maharashtra",
  },
  {
    fullname: "Vihaan Patel",
    dob: "1998-09-20",
    sport: "Football",
    state: "Karnataka",
  },
  {
    fullname: "Ishaan Verma",
    dob: "2002-07-10",
    sport: "Badminton",
    state: "Tamil Nadu",
  },
  {
    fullname: "Rohan Mehta",
    dob: "1997-12-03",
    sport: "Hockey",
    state: "Punjab",
  },
  {
    fullname: "Kabir Joshi",
    dob: "1995-08-30",
    sport: "Wrestling",
    state: "Haryana",
  },
  {
    fullname: "Arjun Das",
    dob: "2001-03-25",
    sport: "Boxing",
    state: "West Bengal",
  },
  {
    fullname: "Devansh Gupta",
    dob: "1999-04-18",
    sport: "Shooting",
    state: "Uttar Pradesh",
  },
  {
    fullname: "Aditya Rao",
    dob: "2003-11-11",
    sport: "Tennis",
    state: "Goa",
  },
  {
    fullname: "Reyansh Reddy",
    dob: "1996-06-07",
    sport: "Athletics",
    state: "Telangana",
  },
  {
    fullname: "Kian Kulkarni",
    dob: "2004-02-14",
    sport: "Table Tennis",
    state: "Madhya Pradesh",
  },
  {
    fullname: "Aryan Mishra",
    dob: "1994-10-05",
    sport: "Swimming",
    state: "Rajasthan",
  },
  {
    fullname: "Vivaan Nair",
    dob: "2000-01-23",
    sport: "Basketball",
    state: "Kerala",
  },
  {
    fullname: "Rudra Bhatt",
    dob: "1993-07-29",
    sport: "Volleyball",
    state: "Gujarat",
  },
  {
    fullname: "Ahaan Roy",
    dob: "1998-05-17",
    sport: "Weightlifting",
    state: "Assam",
  },
  {
    fullname: "Dhruv Singh",
    dob: "1997-09-21",
    sport: "Gymnastics",
    state: "Chhattisgarh",
  },
  {
    fullname: "Kushal Kapoor",
    dob: "2001-12-09",
    sport: "Kabaddi",
    state: "Jharkhand",
  },
  {
    fullname: "Parth Yadav",
    dob: "2003-08-02",
    sport: "Cycling",
    state: "Uttarakhand",
  },
  {
    fullname: "Veer Saxena",
    dob: "1995-04-28",
    sport: "Chess",
    state: "Bihar",
  },
  {
    fullname: "Samar Sen",
    dob: "1999-03-15",
    sport: "Archery",
    state: "Odisha",
  },
  {
    fullname: "Ronit Paul",
    dob: "1996-06-19",
    sport: "Judo",
    state: "Tripura",
  },
  {
    fullname: "Yug Sharma",
    dob: "2002-11-22",
    sport: "Golf",
    state: "Himachal Pradesh",
  },
  {
    fullname: "Eshaan Choudhury",
    dob: "1997-01-10",
    sport: "Kho Kho",
    state: "Manipur",
  },
  {
    fullname: "Harsh Jain",
    dob: "1998-02-27",
    sport: "Polo",
    state: "Meghalaya",
  },
  {
    fullname: "Aadiv Kumar",
    dob: "1993-09-12",
    sport: "Carrom",
    state: "Nagaland",
  },
  {
    fullname: "Tejas Sinha",
    dob: "2000-07-04",
    sport: "Shooting",
    state: "Arunachal Pradesh",
  },
  {
    fullname: "Nihal Dutta",
    dob: "1996-10-08",
    sport: "Cricket",
    state: "Mizoram",
  },
  {
    fullname: "Rishit Mukherjee",
    dob: "1995-12-25",
    sport: "Football",
    state: "Sikkim",
  },
  {
    fullname: "Shivam Sen",
    dob: "2001-04-11",
    sport: "Badminton",
    state: "Andaman and Nicobar Islands",
  },
  {
    fullname: "Neil Bhargava",
    dob: "1994-05-29",
    sport: "Hockey",
    state: "Chandigarh",
  },
  {
    fullname: "Varun Kapoor",
    dob: "1999-06-18",
    sport: "Wrestling",
    state: "Dadra and Nagar Haveli and Daman and Diu",
  },
  {
    fullname: "Siddharth Rathi",
    dob: "1997-03-21",
    sport: "Boxing",
    state: "Delhi",
  },
  {
    fullname: "Anay Vashisth",
    dob: "2003-10-09",
    sport: "Tennis",
    state: "Lakshadweep",
  },
  {
    fullname: "Shlok Sharma",
    dob: "1998-08-16",
    sport: "Athletics",
    state: "Puducherry",
  },
  {
    fullname: "Nirvaan Saxena",
    dob: "2002-02-06",
    sport: "Table Tennis",
    state: "Ladakh",
  },
  {
    fullname: "Aryavir Goel",
    dob: "1996-07-24",
    sport: "Swimming",
    state: "Jammu and Kashmir",
  },
  {
    fullname: "Reetesh Soni",
    dob: "2000-09-02",
    sport: "Basketball",
    state: "Goa",
  },
  {
    fullname: "Utsav Pandey",
    dob: "1995-12-11",
    sport: "Volleyball",
    state: "Gujarat",
  },
  {
    fullname: "Kunal Trivedi",
    dob: "1999-01-08",
    sport: "Weightlifting",
    state: "Maharashtra",
  },
];
